### ISSUE TITLE
different results to admin-build

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/shopware-plugin-compiler#2]
Using this, we're experiencing different results in admin.

Using plugin-compiler:
![image](https://user-images.githubusercontent.com/135993/89020140-b6f1c900-d31e-11ea-91cf-a9e4aff8b33c.png)

Correct and result with admin-build:
![image](https://user-images.githubusercontent.com/135993/89020172-c53fe500-d31e-11ea-91f6-a7b58792fc08.png)

Additionally, using plugin-compiler **randomly** crashes cms-administration.

**Comment by shyim** [comment]
Use https://github.com/FriendsOfShopware/platform-plugin-dev-docker
